variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - deploy

sausage-store-deploy:
  image: argoproj/argocd:v2.3.3
  stage: deploy
#  when: manual

    
  script:
  - argocd --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER app set sausage-store-alexander-volokhov -p backend.image.tag=latest
  - argocd --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER app sync sausage-store-alexander-volokhov 
  rules:
    - changes:
      - kubernetes/**/*
      - .gitlab-ci.yml
  environment:
     name: PRODUCTION
     url: https://02-aleksandr-volokhov.k8s.praktikum-services.tech/
#!!