variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - deploy

sausage-store-deploy:
  image: ubuntu:16.04
  stage: deploy
#  when: manual
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - cp kubectl /usr/local/bin/
    - chmod +x /usr/local/bin/kubectl
    - echo "$KUBECONFIG" >> kubeconfig
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    - chmod 777 get_helm.sh
    - ./get_helm.sh
  script:
    - helm repo add nexus ${NEXUX_REPO_URL} --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_USER}
    - helm repo update
    - helm upgrade --install sausage-store sausage-store --version 0.1.2  --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_USER} --atomic
    - rm -f kubeconfig
  rules:
    - changes:
      - kubernetes/**/*
      - .gitlab-ci.yml
  environment:
     name: PRODUCTION
     url: https://02-aleksandr-volokhov.k8s.praktikum-services.tech/
#!!