---
apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
    - image: vault
      name: vault
      imagePullPolicy: IfNotPresent
      env:
        VAULT_SERVER: "http://127.0.0.1:8200"
        VAULT_ADDR: "http://127.0.0.1:8200"
      ports:
        - name: vault
          containerPort: 8200
      
